For Carbs Daily/Entry List, changed to specific closures for refreshable support
For Carbs Daily/Entry List, changed to specific closures for refreshable support.

TODO: FIXED: WARNING in xCode 13.4.1 on my Mac, but ERROR in xCode 13.2.1 on GitHub.
ERROR: Converting non-sendable function value to '@Sendable () async -> Void' may introduce data races.